export type Clinics = Partial<{
  "Long Name Version": string;
  "Typeform registration link": string;
  PMS: string;
  "Meta-title": string;
  "Meta-description": string;
  slug: string;
  Website: string;
  "Clinic Name": string;
  Display_on_web: string;
  "link to clinic suburb page": string;
  "Full Address": string;
  City: string;
  Suburb: string;
  State: string;
  Postcode: string;
  Email: string;
  Phone: string;
  nearby1_txt: string;
  nearby1_link: string;
  nearby2_txt: string;
  nearby2_link: string;
  nearby3_txt: string;
  nearby3_link: string;
  nearby4_txt: string;
  nearby4_link: string;
  "About Clinic": string;
}>[];
